# Bitcoin price service with Spring Reactive
info:
  app:
    name: Bitcoin price Service
    description: Get price of bitcoinReactive every 10 secs
    version: 1.0.0

# Spring boot actuator configurations
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics

# Configure Logging
logging:
  level:
    root: INFO
    com.toomuch2learn: DEBUG
    org.springframework: INFO
    org.apache.catalina: ERROR

# Display auto-configuration report when running a Spring Boot application
#debug: true

# Configure Spring specific properties
spring:
  # Enable/Disable hot swapping
  devtools:
    restart:
      enabled: true
      log-condition-evaluation-delta: false

  # Datasource Configurations
  h2:
    console:
      enabled: true
      path: /h2

  # R2DBC Configuration
  r2dbc:
    url: r2dbc:h2:mem:///bitcoindb
    username: sa
    password:
    initialization-mode: always
